name: testing actions releases

on:
  push:
    tags: [ 'v*.*', 'v*.*.*', 'v*.*.*-*' ]
    branches: [ 'main' ]

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
    - name: create release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
      if: startsWith(github.ref, 'refs/tags/')

  build:
    needs: [ release ]
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        goos: [ "linux", "darwin" ]
        goarch: [ "amd64", "arm64" ]

    steps:
    - uses: actions/checkout@v3

    - name: install make and file
      run: sudo apt-get -qq update && sudo apt-get install -y -qq make file

    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: build
      run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make build

    - name: build output
      run: file bin/*

    - name: upload release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/*
      if: startsWith(github.ref, 'refs/tags/')
